### ISSUE TITLE
"Player is not injured or not in ship" on v55 regardless if they are or not

### ISSUE THREAD

**Issue by dopadream** [DarkSnakeX/DanceHealingOnShip#1]
Check for injured/on ship seems to be broken in v55. Probably something to do with the ship changes for the Cruiser, I don't know.

**Comment by DarkSnakeX** [comment]
This mod doesn't support v55 at this moment, will be updated when I have time.

**Comment by dopadream** [comment]
Adding onto this, it works sometimes, but other times it does not. I think the cooldown is broken

**Comment by DarkSnakeX** [comment]
Hi again I am testing the mod in the new version but I cant seem to reproduce the problem, can you provide more info?

**Comment by DarkSnakeX** [comment]
I am deploying a new version with a new HUD that it should display correctly how much health have you healed. Let me know if it stills doesn't work properly.
